import type { PropertyDomain } from "./index.js";

export const weather: PropertyDomain = {
  name: "weather",
  displayName: "Weather",
  stateFields: {
    temperature: { type: "number", description: "Current temperature" },
    apparent_temperature: { type: "number", description: "Feels-like temperature" },
    humidity: { type: "number", description: "Relative humidity (0-1)", min: 0, max: 1 },
    condition: { type: "string", description: "Weather condition: clear, rain, snow, sleet, cloudy, partly-cloudy, fog, wind" },
    icon: { type: "string", description: "Dark Sky icon key (e.g. clear-day, partly-cloudy-night)" },
    wind_speed: { type: "number", description: "Wind speed" },
    wind_bearing: { type: "number", description: "Wind direction in degrees (0-359)", min: 0, max: 359 },
    wind_gust: { type: "number", description: "Wind gust speed" },
    pressure: { type: "number", description: "Barometric pressure (hPa)" },
    dew_point: { type: "number", description: "Dew point temperature" },
    cloud_cover: { type: "number", description: "Cloud cover fraction (0-1)", min: 0, max: 1 },
    visibility: { type: "number", description: "Visibility distance (km)" },
    uv_index: { type: "number", description: "UV index", min: 0 },
    precip_intensity: { type: "number", description: "Precipitation intensity (mm/h)", min: 0 },
    precip_probability: { type: "number", description: "Precipitation probability (0-1)", min: 0, max: 1 },
    precip_type: { type: "string", description: "Precipitation type: rain, snow, sleet, or null" },
  },
  commandFields: {},
  features: [
    "current",
    "hourly_forecast",
    "daily_forecast",
    "alerts",
  ],
  roles: ["forecast_provider", "weather_station"],
  queryable: {
    params: {
      from: { type: "number", description: "Start of time range (epoch ms)" },
      to: { type: "number", description: "End of time range (epoch ms)" },
      granularity: { type: "string", description: "Forecast granularity: hourly or daily" },
    },
    itemFields: {
      id: { type: "string", description: "Forecast item ID (e.g. hourly-1709312400 or daily-1709280000)" },
      start: { type: "number", description: "Start time (epoch ms)" },
      end: { type: "number", description: "End time (epoch ms)" },
      granularity: { type: "string", description: "Item granularity: hourly or daily" },
      temperature: { type: "number", description: "Temperature (hourly: point value, daily: high)" },
      temperature_low: { type: "number", description: "Daily low temperature (null for hourly)" },
      apparent_temperature: { type: "number", description: "Feels-like temperature" },
      humidity: { type: "number", description: "Relative humidity (0-1)" },
      condition: { type: "string", description: "Weather condition" },
      icon: { type: "string", description: "Dark Sky icon key" },
      wind_speed: { type: "number", description: "Wind speed" },
      wind_bearing: { type: "number", description: "Wind direction (0-359)" },
      wind_gust: { type: "number", description: "Wind gust speed" },
      pressure: { type: "number", description: "Barometric pressure (hPa)" },
      dew_point: { type: "number", description: "Dew point temperature" },
      cloud_cover: { type: "number", description: "Cloud cover (0-1)" },
      visibility: { type: "number", description: "Visibility distance (km)" },
      uv_index: { type: "number", description: "UV index" },
      precip_intensity: { type: "number", description: "Precipitation intensity (mm/h)" },
      precip_probability: { type: "number", description: "Precipitation probability (0-1)" },
      precip_type: { type: "string", description: "Precipitation type" },
      sunrise: { type: "number", description: "Sunrise time epoch ms (daily only, null for hourly)" },
      sunset: { type: "number", description: "Sunset time epoch ms (daily only, null for hourly)" },
    },
    description: "Query weather forecast data within a time range, optionally filtered by granularity (hourly/daily)",
  },
};
